### ISSUE TITLE
issue #1

### ISSUE THREAD

**Issue by srs231198** [open-source-club-utd/open-source-club-utd.github.io#1]
I'm trying to deploy the website on netlify and I keep running into problems with something called a .nvmrc file that needs to be in the root directory.

**Comment by ckhawks** [comment]
https://www.netlify.com/docs/#nodejs-including-react

"You also need a .nvmrc file at the base of your project to tell Netlify which version of NodeJS to use."

**Comment by ATechAdventurer** [comment]
Addressed in PR #5
